### PR TITLE
Test Mac OS X on Travis

### LINKED ISSUE #121: Test failures on Mac OS X
Not really an issue, more fyi:

	There were 3 failures:

	1) React\Tests\Socket\FunctionalSecureServerTest::testEmitsErrorIfConnectionIsCancelled
	Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
	Method was expected to be called 1 times, actually called 0 times.

	2) React\Tests\Socket\FunctionalTcpServerTest::testEmitsConnectionEvenIfConnectionIsCancelled
	Expectation failed for method name is equal to <string:__invoke> when invoked 1 time(s).
	Method was expected to be called 1 times, actually called 0 times.

	3) React\Tests\Socket\UnixConnectorTest::testValid
	Failed asserting that Binary String: 0x756e69783a2f2f000000000000000000000000000000 is null.

	/Users/andig/Documents/htdocs/react-socket/tests/UnixConnectorTest.php:62

### PR DESCRIPTION
**Pull request by clue**
Squashed by @clue, originally from reactphp/socket#124

~~~Marking this as WIP for now until tests are less flaky and outstanding test failures have been resolved.~~~

Resolves / closes #121

### CODE REVIEW

**Comment by clue** [comment]
I've updated this to skip platform-specific (Linux) tests on other platforms (Mac OS X). This is now ready for review :shipit:

**Comment by andig** [comment]
> I've updated this to skip platform-specific (Linux) tests on other platforms (Mac OS X). This is now ready for review 

Alternatively, you could mark the tests with `@group` and have the OSX build run with `--excludeGroup`. It's not quite clear why exactly these two tests should be run on Linux only (and not e.g. OSX)?

**Comment by clue** [comment]
These two tests specifically test system behavior ("how does the server side react to when a client connection is started and aborted immediately without waiting for the connection to be fully established?") and do not really test things specific to this library at all. We know this is how Linux behaves but do not have any reliable source for other platforms, so I think it makes sense to just skip this for now other platforms until we have a better understanding of this.

Our library is known to work perfectly fine on Mac OS X and I think we should emphasize this (failing system specific tests give a wrong impression here). However, our resources to test this on other platforms are limited, I for one for not have a Mac at hand. Given how long this has gone unnoticed, I think it should be sufficient to rely on Travis to spot future regressions here.

@andig I think using a `@group` makes sense for tests that can/should explicitly be toggled. In this particular case I think it's a sane default to always skip this for Mac OS X :+1:

**Comment by WyriHaximus** [comment]
@clue @jsor Do we want to test against OS X on all our other packages as well?

**Comment by clue** [comment]
@WyriHaximus I don't really have a use for this unless anybody brings up any issues, but if you feel it's worth it, I'd say for got it :+1:

**Pull request merged**
