### PR TITLE
Add link for previous version docs

### PR DESCRIPTION
**Pull request by Nek-**
You have a good velocity in development theses days. But some projects use a previous version and the doc looks wrong but it's not!

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Thanks for filing this PR, you've made an excellent point there 👍 . Currently I'm not 100% sold on the location, personally I think it would be better to put it right above or right below the ToC. The first thing you read now is where to find older versions of the docs rather then what this package does.

**Comment by Nek-** [comment]
Please wait this is badly formatted ! ^^

**Comment by Nek-** [comment]
@WyriHaximus here it is with a better formatting. And the inspiration of formatting comes from guzzle : https://github.com/guzzle/guzzle#version-guidance

**Comment by clue** [comment]
Thanks for filing this PR @Nek-, I agree with @WyriHaximus that you're making a very good point here :+1: Do you feel this is still relevant now that development has slowed down a bit and this component is now deprecated (#86)?

**Comment by jsor** [comment]
I'd rather add something like that to reactphp.org, so i'm 👎 for adding this so prominently to the readme.

The following screenshot is from a local branch which i'm going to do a PR for reactphp/website when i find some time to finish it.

bildschirmfoto 2017-09-04 um 21 22 09

**Comment by Nek-** [comment]
Looks like a good idea. Only if you redirect the user directly to reactphp.org from the README. Which is not the case as you actually uses the README to generate reactphp.org.

This makes me sceptic and may still create a lot of frustration. (that was mine before I created this PR haha)

... Especially since the development is so heavy. :D cc  @clue

**Comment by clue** [comment]
@jsor's suggestion from above has been implemented via https://github.com/reactphp/website/pull/20 :shipit: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Pull request closed without merging**
