### PR TITLE
Added phpunit to the dev requirements. Fixed test cases to no longer …

### PR DESCRIPTION
**Pull request by SamMousa**
…use deprecated `getMock` function.

### CODE REVIEW

**Comment by SamMousa** [comment]
Have changed / partially reverted this to instead require PHPUnit 4.8

**Comment by clue** [comment]
Personally, I'm undecided on this, but I know similar patches have been rejected in the past.

I guess this worth discussing in the meta repo?

**Comment by SamMousa** [comment]
@clue What do you mean, you don't think we should use `require-dev`?

I tried to run tests having installed phpunit 5 locally and they failed; how would I find out what version of PHPUnit I should use if it's not in require-dev?

**Comment by clue** [comment]
I think there are valid reasons both pro and contra adding `require-dev` and you've listed a very valid reason pro imho. I would suggest discussing this in the main meta repo instead, because this does not apply to this component alone.

**Comment by clue** [comment]
Closed via #57

**Pull request closed without merging**
